### ISSUE TITLE
Descriptors cannot not be created directly.

### ISSUE THREAD

**Issue by Roushelfy** [HirojiFukuyama/pkuhole#2]
(pkuhole) D:\桌面\python\pkuhole-master>streamlit run app.py
Traceback (most recent call last):
  File "D:\anaconda\envs\pkuhole\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\anaconda\envs\pkuhole\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\anaconda\envs\pkuhole\Scripts\streamlit.exe\__main__.py", line 4, in <module>
  File "D:\anaconda\envs\pkuhole\lib\site-packages\streamlit\__init__.py", line 48, in <module>
    from streamlit.proto.RootContainer_pb2 import RootContainer
  File "D:\anaconda\envs\pkuhole\lib\site-packages\streamlit\proto\RootContainer_pb2.py", line 33, in <module>
    _descriptor.EnumValueDescriptor(
  File "D:\anaconda\envs\pkuhole\lib\site-packages\google\protobuf\descriptor.py", line 755, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates

**Comment by HirojiFukuyama** [comment]
先看一下Environment里面的包有没有安装到目录
